Revert "Update ziptool-tests to use test config auto-gen"
This reverts commit 309b9279341f01be5177c0f9b891dba7c55f70bd.

Reason for revert: broke the ndk build

Buildbot Version: androidbuild_buildbot_20200914.00_RC02
Machine: abfarm209
OUT_DIR=out DIST_DIR=/buildbot/dist_dirs/aosp-master-linux-ndk/6885151 build/soong/scripts/build-ndk-prebuilts.sh
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: system/libziparchive/Android.bp:211:1: dependency "cli-test" of "ziptool-tests" missing variant:
  os:android, arch:arm_armv7-a
available variants:
  os:linux_glibc, arch:x86_64
  os:android, image:, arch:arm64_armv8-a(alias to os:android, image:, arch:arm64_armv8-a, sdk:, version:)
  os:android, image:, arch:arm64_armv8-a, sdk:(alias to os:android, image:, arch:arm64_armv8-a, sdk:, version:)
  os:android, image:, arch:arm64_armv8-a, sdk:, version:
  os:android, image:, arch:arm64_armv8-a, sdk:, version:latest(alias to os:android, image:, arch:arm64_armv8-a, sdk:, version:)

Change-Id: I9cfed7d96abd6615d2c23e8eddba7362213fb71d